### ISSUE TITLE
你好， 想请教几个问题

### ISSUE THREAD

**Issue by Kevinl7** [jkchao/vue-blog#10]
我用npm run generate打包的静态文件
index.html里面的标签都没闭合。。。。 

其他页面打包正常。。。

还有怎么在nuxt项目 设置webpack打包配置？

**Comment by jkchao** [comment]
我试了下，正常闭合。。。

配置相关可以看这个： https://nuxtjs.org/api/configuration-build

**Comment by Kevinl7** [comment]
哎， 好奇怪啊。。 。谢谢， 在问下，你的网站是使用静态资源部署的么?

**Comment by jkchao** [comment]
@Kevinl7 不是额

**Comment by Kevinl7** [comment]
哦哦， 你是后端也写在nuxt项目下面是么？

**Comment by jkchao** [comment]
分开的，api 在 node-koa 项目里。

**Comment by Kevinl7** [comment]
那静态部署也是可以请求到数据的， 服务端部署有什么优点呢？

**Comment by jkchao** [comment]
静态部署大概相当于  spa 形式的吧，先请求一个空的 html，再请求数据填充进去。
服务端的话应该是 ssr 吧。https://jkchao.cn/article/5a11155fb520d115154c8fa1 ， 可以看下这个。

**Comment by Kevinl7** [comment]
非常感谢， 使用nuxt 但是静态部署的话  和没用一样了。。 解决不了seo问题。

**Comment by jkchao** [comment]
我也不确定静态部署是不是 spa 的形式。。。
但是肯定是没有了服务端部署的优势的。😂

**Comment by Kevinl7** [comment]
哈哈，谢谢。 我用服务端部署试下。。

**Comment by Kevinl7** [comment]
老哥， 再问下 我用服务端部署，  生成的文件在哪？ 我想部署到服务器看下。

**Comment by jkchao** [comment]
https://nuxtjs.org/guide/commands 这个上面有的

**Comment by Kevinl7** [comment]
我不明白部署这块， 是把整个项目 传到我的阿里云服务器里？ 然后用pm2守护启动， 然后作反向代理 是这个流程么？

**Comment by jkchao** [comment]
两种方式应该都行：
- 整个项目传上去，在服务器上 install -> build -> start。
- 也可以在本地 build 出来，然后传到服务器上 start。

**Comment by Kevinl7** [comment]
我是本地build的 然后好像并没有生成什么文件？ 传什么文件？

**Comment by Kevinl7** [comment]
build的之后 node-modules依赖包是不是就不需要了？？？

**Comment by jkchao** [comment]
build 之后有个 dist 文件夹。
嗯，build 之后 node-modules 依赖就不需要了。

**Comment by Kevinl7** [comment]
我 build之后 并没有生成 dist文件夹。。
只有 generate会生成dist文件夹。。。
![image](https://user-images.githubusercontent.com/22197685/37752798-b26df8dc-2dd4-11e8-82db-fce8cb02c5de.png)

**Comment by jkchao** [comment]
说错了。。。
build 之后会有一个 build 文件夹与 .nuxt 文件夹。

**Comment by Kevinl7** [comment]
我只有 .nuxt文件夹。。  。
我的理解是 应该是  生成这个文件夹后 在里面新建一个  package.json  复制官方指令
就可以执行了。  但是我操作不行，报错。

**Comment by Kevinl7** [comment]
老哥，  我打包后 为什么没有 build文件夹？？ 我用的nuxt 1.0.0版 。 
这也应该是 导致我 去掉 node_modules包 运行不了的原因吧。。

**Comment by jkchao** [comment]
nuxt 有些模版好像不会出 build 文件夹。

**Comment by Kevinl7** [comment]
我用的starter-template, 老哥 知道怎么解决这个问题么？  总不能我把node_modules包全部上传吧？ 
太大了。。 老哥， 你用的哪个模板？

**Comment by jkchao** [comment]
你可以把相关文件传到服务器上，到服务器上装包再启动。
我用的 koa 那个模板。
