### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by AyumiKai** [jkchao/vue-blog#2]
我的node版本是v8.1.3，系统是Mac,报  (node:2587) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor
请问下大大怎么解决

**Comment by jkchao** [comment]
Node-koa项目七牛参数没配置吧？
