### ISSUE TITLE
想请教一下，报错window is not defined咋解决？

### ISSUE THREAD

**Issue by zp1112** [jkchao/vue-blog#3]
![image](https://user-images.githubusercontent.com/14245159/31364899-7cc5fa32-ad9a-11e7-9c3c-59782386dd4d.png)

**Comment by jkchao** [comment]
if (typeof window !== 'undefined') {
 //  in browser
}

**Comment by jkchao** [comment]
@zp1112 
if (typeof window !== 'undefined') {
 //  in browser
}
