### ISSUE TITLE
你好，想请教一下，你的博客中没有出现xhr请求，是如何做到的？

### ISSUE THREAD

**Issue by zp1112** [jkchao/vue-blog#4]
就是浏览器的network没有发起一些文章列表的异步请求，是因为做了服务器端渲染么？在后台做的请求？但是我在开发环境下还是有xhr请求的
![image](https://user-images.githubusercontent.com/14245159/31375529-7a0a162c-add4-11e7-941d-bf558f0c1ee1.png)

**Comment by jkchao** [comment]
@zp1112 
可以看看这个 https://zh.nuxtjs.org/api/pages-fetch
