### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by ziming2018** [jkchao/vue-blog#5]
(node:3811) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: __WEBPACK_IMPORTED_MODULE_2_nuxt___default.a is not a constructor

**Comment by jkchao** [comment]
@ziming2018 信息太少了

**Comment by ziming2018** [comment]
git clone 然后 npm install 接着 npm run dev

**Comment by jkchao** [comment]
@ziming2018 服务端起来了？

**Comment by ziming2018** [comment]
@jkchao 服务端运行起来了

**Comment by ziming2018** [comment]
@jkchao 服务端没问题

**Comment by jkchao** [comment]
@ziming2018 运行环境是什么

**Comment by ziming2018** [comment]
@jkchao ubuntu17.10

**Comment by ziming2018** [comment]
@jkchao 好像是nuxt.js的问题?

**Comment by ziming2018** [comment]
??

**Comment by jkchao** [comment]
@ziming2018 node 版本 npm 版本

**Comment by ziming2018** [comment]
node --version
v8.8.1

npm --version
5.4.2

**Comment by ziming2018** [comment]
我用最新版再试试

**Comment by jkchao** [comment]
@ziming2018 解决了吧？

**Comment by ziming2018** [comment]
@jkchao 没解决
