### ISSUE TITLE
正式环境如何发布部署？

### ISSUE THREAD

**Issue by vqlai** [jkchao/vue-blog#7]
这个blog有CLIENT，ADMIN，SERVICE三个部分，请问正式环境是如何进行部署才能将这三个正确运行起来？能具体解释一下么？

**Comment by jkchao** [comment]
admin 做静态文件处理，service client 各起一个 node 进程，nginx 反向代理。

**Comment by vqlai** [comment]
你好，请问在正式环境服务器里如何起两个node进程并且绑定到不同的子域名里？nginx反向代理又是如何做的呢?谢谢。

**Comment by jkchao** [comment]
@vqlai 
```sheel
server {
listen       80; 
server_name  A.ABC.com; 
}

server {
listen       80; 
server_name  B.ABC.com; 
}

```

**Comment by vqlai** [comment]
看不明白，能详细解释一下么？谢谢。。。

**Comment by jkchao** [comment]
@vqlai 网上有的，自己去找吧。

**Comment by vqlai** [comment]
好的，谢谢

**Comment by jkchao** [comment]
@vqlai  Enjoy your code.
