### ISSUE TITLE
开发disqus的功能是否遇到障碍

### ISSUE THREAD

**Issue by POJOa** [jkchao/vue-blog#9]
新年好。
您的项目很不错，要是早点发现我就不造轮子了。
我最近也在用nuxt写blog，在加载另一个评论插件（livere）的时候遇到了问题。
请问您在这个项目里移除了disqus的功能，是否由于nuxt当前的某些功能限制？

我的问题具体说来，就是在某些case里，异步加载到div里的iframe会被突然移除，我暂时还不知道是谁把这个div的child都突然清空了...
尽管我并不认为这是nuxt的锅，但姑且还是来问一下。

**Comment by jkchao** [comment]
@POJOa 
新年好。
不用 disqus 只是因为它在墙外。😂
ifrane 被移除应该不是 nuxt 的问题。当初我用的时候，好像并没有这问题。- -

**Comment by POJOa** [comment]
对是我的锅...
